services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      # I'm not gonna use a .env to this configs
      # but is expected that you use it, so be careful.
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbitmq@my-rabbit
      - rabbitmq_log:/var/log/rabbitmq

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev"]

volumes:
  rabbitmq_data:
  rabbitmq_log:
