services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    hostname: fintech-rabbitmq
    container_name: fintech-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      # I'm not gonna use a .env to this configs
      # but is expected that you use it, so be careful.
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia/rabbitmq@my-rabbit
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      - fintech

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: fintech-keycloak
    container_name: fintech-keycloak
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_PROXY: edge
    command:
      [
        "start-dev",
        "--hostname=http://fintech-keycloak:8081",
        "--hostname-admin=http://fintech-keycloak:8081",
      ]
    networks:
      - fintech

  eureka-server:
    build:
      context: ../applications/eureka-server
      dockerfile: Dockerfile
    image: fintech-eureka-server
    hostname: fintech-eureka-server
    container_name: fintech-eureka-server
    ports:
      - "8761:8761"
    networks:
      - fintech

  client-api:
    build:
      context: ../applications/client-api
      dockerfile: Dockerfile
    image: fintech-client-api
    hostname: fintech-client-api
    container_name: fintech-client-api
    networks:
      - fintech
    depends_on:
      - keycloak
      - eureka-server
      - rabbitmq

  card-api:
    build:
      context: ../applications/card-api
      dockerfile: Dockerfile
    image: fintech-card-api
    hostname: fintech-card-api
    container_name: fintech-card-api
    networks:
      - fintech
    depends_on:
      - keycloak
      - eureka-server
      - rabbitmq

  credit-validator-api:
    build:
      context: ../applications/credit-validator-api
      dockerfile: Dockerfile
    image: fintech-credit-validator-api
    hostname: fintech-credit-validator-api
    container_name: fintech-credit-validator-api
    networks:
      - fintech
    depends_on:
      - keycloak
      - eureka-server
      - rabbitmq

  api-gateway:
    build:
      context: ../applications/api-gateway
      dockerfile: Dockerfile
    image: fintech-api-gateway
    hostname: fintech-api-gateway
    container_name: fintech-api-gateway
    ports:
      - "8080:8080"
    networks:
      - fintech
    depends_on:
      - keycloak
      - eureka-server
      - rabbitmq
      - credit-validator-api
      - card-api
      - client-api

volumes:
  rabbitmq_data:
  rabbitmq_log:

networks:
  fintech:
